---
# handlers file for ansible-roles
 - name: start httpd service
   service:
     name: httpd
     state: started
   when: ansible_nodename=="ansible-node1"

 - name: start apache2 service
   service:
     name: apache2
     state: started
   when: ansible_nodename=="ansible-ubuntu-node"
