---
- name: notify and handlers
  hosts: aws
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    notify: start service httpd
  handlers:
  - name: start service httpd
    service:
      name: httpd
      state: started
