---
- name: install and start services
  hosts: all
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_nodename=="ansible-node1"
    notify: start httpd service
  - name: install apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_nodename=="ansible-ubuntu-node"
    notify: start apache2 service
  - name: copy html file
    copy:
      src: /opt/appaccess.html
      dest: /var/www/html
      mode: 0777

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_nodename=="ansible-node1"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_nodename=="ansible-ubuntu-node"
