---
- name: install and start service using tags
  hosts: all
  become: true
  tasks:
  - name: install httpd package on RHEL server
    yum:
      name: httpd
      state: installed
    when: ansible_nodename=="Ansible-RHEL-node"
    tags: install_service
  - name: install apache2 on ubuntu server
    apt:
      name: apache2
      state: present
    when: ansible_nodename=="ansible-ubuntu-node"
    tags: install_service
  - name: start service on RHEL server
    service:
      name: httpd
      state: started
    when: ansible_nodename=="Ansible-RHEL-node"
    tags: start_service
  - name: start service on ubuntu server
    service:
      name: apache2
      state: started
    when: ansible_nodename=="ansible-ubuntu-node"
    tags: start_service
